config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  get 'users/index'
  root 'users#welcome'
  get 'users/show'
  get 'users/find'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @users = User.all
  end

  def welcome
  end

  def new
    @user = User.new
  end

  def find
    @user = if params[:search]
      User.where("name LIKE ?", "%#{params[:search][0..2]}%")
    else 
      User.all
    end
  end

  def create
    user =  User.create(user_params)
    redirect_to('/users/index/')
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name, :surname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleanUp</title>  
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main>
      <%= yield %>
    </main>
    <script src="https://kit.fontawesome.com/094c1ebca5.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/find.html.erb
<%= stylesheet_link_tag "find.css" %>
<header>
  <ul>
    <a href="<%= users_index_path %>"><i class="fa-solid fa-house off"></i></a>
    <a href="<%= users_find_path %>"><i class="fa-solid fa-magnifying-glass on"></i></a>
    <a><i class="fa-solid fa-user off"></i></a>
  </ul>
</header>
<section id="welcome">
  <div id="pictures_profils">
      <%= image_tag "1673041909611.jpg" %>
  </div>
  <p id="name">Rechercher</p>
  <h1 id="pitch">Des experts pour redonner de l'eclat à votre interieur</h1>
  <div class="d">
     <%= form_tag(users_find_path, method: :get) do %>
        <%= text_field_tag :search, params[:search], placeholder:'Rechercher une ville' %>
    <% end %>
  </div>
</section>

<section id="likes_profiles">
  <% @user.each do |item| %>
    <article class="users_profils">
      <div class="users_profils_top">
        <div class="users_profils_img">
          <%= image_tag "young-and-beautiful-woman-in-pink-warm-sweater-natural-look-smiling-portrait-on-isolated-long-hair.jpg" %>
        </div>
        <div class="users_profils_contents">
          <h3 class="name"><%= item.name %></h3>
          <p class="days_work">24€ <sub>/h</sub><span class="days"> | </span>7j / 7</p>
          <p class="locate"><i class="fa-solid fa-location-dot"></i>Paris</p>
        </div>
      </div>
      <div class="users_profils_description">
        <p>Cristina 46ans, 5 enfants, femme au foyer, je suis  à la recherche d'un poste de femme de ménage.</p>
      </div>
      <div class="users_profils_bottom">
        <a>Voir le profil</a>
      </div>
    </article>
  <% end %>
</section>

app/views/users/index.html.erb
<%= stylesheet_link_tag "index.css" %>
<header>
  <ul>
    <a href="<%= users_index_path %>"><i class="fa-solid fa-house on"></i></a>
    <a href="<%= users_find_path %>"><i class="fa-solid fa-magnifying-glass off"></i></a>
    <a><i class="fa-solid fa-user off"></i></a>
  </ul>
</header>
<section id="welcome">
  <div id="pictures_profils">
    <%= image_tag "1673041909611.jpg" %>
  </div>
  <p id="name">Hey Matis Bevilacqua !</p>
  <h1 id="pitch">Des experts pour redonner de l'eclat à votre interieur</h1>
  <a id="get_profil">Accéder à mon profil</a>
</section>
<section id="likes_profiles">
  <h2 id="likes_title">Vous avez aimé</h2>
  <% @users.each do |item| %>
    <article class="users_profils">
      <div class="users_profils_top">
        <div class="users_profils_img">
          <%= image_tag "young-and-beautiful-woman-in-pink-warm-sweater-natural-look-smiling-portrait-on-isolated-long-hair.jpg" %>
        </div>
        <div class="users_profils_contents">
          <h3 class="name"><%= item.name %></h3>
          <p class="days_work">24€ <sub>/h</sub><span class="days"> | </span>7j / 7</p>
          <p class="locate"><i class="fa-solid fa-location-dot"></i>Paris</p>
        </div>
      </div>
      <div class="users_profils_description">
        <p>Cristina 46ans, 5 enfants, femme au foyer, je suis  à la recherche d'un poste de femme de ménage.</p>
      </div>
      <div class="users_profils_bottom">
        <a>Voir le profil</a>
      </div>
    </article>
  <% end %>
</section>

app/views/users/new.html.erb
<%= stylesheet_link_tag "login" %>
<h1 id="new"><span>Créer</span> mon compte</h1>
<h2 id="client">Vous êtes déja client ? <a id="connect_link">Se connecter</a> </h2>
<%= form_for @user do |f| %>
    <%= f.text_field :name, required:true, placeholder: 'Prénom', class: 'log_form'%>
    <%= f.text_field :surname,required:true,  placeholder:'Nom', class: 'log_form' %>
    <%= f.email_field :email,required:true,  placeholder: 'Adresse email', class: 'log_form' %>
    <%= f.password_field :password,required:true,  placeholder: 'Mot de passe', class: 'log_form' %>
    <button class="next submit" type="submit">Valider</button>
<% end %>

app/views/users/welcome.html.erb
<%= stylesheet_link_tag "welcome" %>